name: Install MS ODBC Driver and PyODBC

# 觸發條件：
# 1. workflow_dispatch: 允許你手動在 GitHub Actions 頁面點擊按鈕執行
# 2. schedule: 在指定時間自動執行 (使用 UTC 時間)
#    - cron: '0 1 * * *'  代表每天 UTC 凌晨 1 點 (台北時間早上 9 點) 執行
# 3. push: 當有程式碼推送到 main 分支時執行 (可選)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main

jobs:
  install-and-verify:
    # 使用最新的 Ubuntu 虛擬主機
    runs-on: ubuntu-latest

    steps:
      # 步驟 1: 將你的 repository 程式碼下載到虛擬主機中
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步驟 2: 設定你需要的 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 你可以更換成需要的版本，例如 '3.10'

      # 步驟 3: 安裝 Microsoft ODBC Driver
      # 將你提供的所有 apt-get 和 curl 指令整合到一個 run 步驟中
      - name: Install Microsoft ODBC Driver 17 for SQL Server
        run: |
          # 更新套件列表
          sudo apt-get -qq update

          # 安裝基本工具
          sudo apt-get -qq install -y curl apt-transport-https

          # 信任 Microsoft GPG 金鑰
          curl -s https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

          # 新增 Microsoft SQL Server 套件庫
          curl -s https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

          # 再次更新套件列表以載入新庫
          sudo apt-get -qq update

          # 接受 EULA 並安裝驅動程式和開發工具
          sudo ACCEPT_EULA=Y apt-get -qq install -y msodbcsql17 unixodbc-dev

      # 步驟 4: 安裝 pyodbc Python 套件
      # 最好是將它寫在 requirements.txt 中，這裡直接安裝作為示範
      - name: Install pyodbc
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc
          # 如果你有 requirements.txt，更推薦使用下面這行
          # pip install -r requirements.txt

      # 步驟 5: 驗證安裝是否成功
      # 這是非常重要的一步，確保驅動程式和 pyodbc 都已正確安裝並能互相溝通
      - name: Verify Installation
        run: |
          echo "Verifying pyodbc and ODBC Drivers..."
          python -c "import pyodbc; print('pyodbc version:', pyodbc.version); print('Available drivers:', pyodbc.drivers())"

      # 步驟 6: (你的主要任務) 執行你自己的 Python 腳本
      # - name: Run Main Python Script
      #   run: python your_script_name.py
      #   env:
      #     # 如果腳本需要帳號密碼，建議使用 GitHub Secrets
      #     DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}